# https://megalinter.io/configuration/
---
VALIDATE_ALL_CODEBASE: true
EXCLUDED_DIRECTORIES:
  - pifm

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS

SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
